;[CONFIG]
;# 生产工厂代码，AT代表奥汀
;生产工厂代码 = AT
;
;# 每批次处理的数量
;每批处理数量 = 100
;
;# ODM厂商代码
;odm = LC
;
;# 获取token的API地址
;token_api = https://api-cn.lenovo.com/token
;
;# 机器序列API
;mathine_api = https://api-cn.lenovo.com/v1.0/supply_chain/ips_guarantee_data/tbl_machine_sequence
;
;# 物料API
;material_api = https://api-cn.lenovo.com/v1.0/supply_chain/ips_guarantee_data/tbl_packing_machine_material
;
;# API的consumer key
;consumer_key = zuuA3GFYEfx1B2Hdngs3V_A19Vca
;
;# API的consumer secret
;consumer_secret = KB3mrXiAMlJoTlqstyXSDniM5osa
;
;# PN的key
;pn_key = 8码
;
;# Lecoo OA3FLAG
;o3_flag =
;
;# Lecoo Windows11 Home Chinese Language
;win_version =
;
;pkid_pn =
;
;sn_key= 装箱条码


 # 测试环境
[CONFIG]
# 生产工厂代码，AT代表奥汀
生产工厂代码 = AT

# 每批次处理的数量
每批处理数量 = 100

# ODM厂商代码
odm = LC

# 获取token的API地址
token_api = https://api-cn-t.lenovo.com/uat/token

# 机器序列API
mathine_api = https://api-cn-t.lenovo.com/uat/v1.0/supply_chain/ips_guarantee_data/tbl_machine_sequence

# 物料API
material_api = https://api-cn-t.lenovo.com/uat/v1.0/supply_chain/ips_guarantee_data/tbl_packing_machine_material

# API的consumer key
consumer_key = CrjifR54rsPeirvatCMBi8oRnUMa

# API的consumer secret
consumer_secret = T3C5Xwtt9Jn_pPv2PIBhs0q8mDwa

# PN的key
pn_key = 8码

# Lecoo OA3FLAG
o3_flag = 870041003

# Lecoo Windows11 Home Chinese Language
win_version = 870041001

pkid_pn =

sn_key= 装箱条码


